/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AIFeatures: typeof import('./src/components/ai/AIFeatures.vue')['default']
    ChatInterface: typeof import('./src/components/ai/ChatInterface.vue')['default']
    ErrorBoundary: typeof import('./src/components/ui/ErrorBoundary.vue')['default']
    EvaluationView: typeof import('./src/components/ai/EvaluationView.vue')['default']
    ExportDialog: typeof import('./src/components/export/ExportDialog.vue')['default']
    FileUpload: typeof import('./src/components/upload/FileUpload.vue')['default']
    GlobalTaskManager: typeof import('./src/components/common/GlobalTaskManager.vue')['default']
    Header: typeof import('./src/components/layout/Header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    LoadingSpinner: typeof import('./src/components/ui/LoadingSpinner.vue')['default']
    MainLayout: typeof import('./src/components/layout/MainLayout.vue')['default']
    MediaPlayer: typeof import('./src/components/player/MediaPlayer.vue')['default']
    MindmapView: typeof import('./src/components/ai/MindmapView.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NInput: typeof import('naive-ui')['NInput']
    PlayControls: typeof import('./src/components/player/PlayControls.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/layout/Sidebar.vue')['default']
    SummaryView: typeof import('./src/components/ai/SummaryView.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    TranscriptionProgress: typeof import('./src/components/transcription/TranscriptionProgress.vue')['default']
    TranscriptionSegment: typeof import('./src/components/transcription/TranscriptionSegment.vue')['default']
    TranscriptionView: typeof import('./src/components/transcription/TranscriptionView.vue')['default']
    UploadProgress: typeof import('./src/components/upload/UploadProgress.vue')['default']
    VideoDownload: typeof import('./src/components/download/VideoDownload.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
